=== lyl123321/MismatchSolution/data/dblp/dblp.dtd
<!ELEMENT dblp (article|inproceedings|proceedings|book|incollection|phdthesis|mastersthesis|www)*>
<!ELEMENT article       (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT inproceedings (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT proceedings   (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT book          (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT incollection  (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT phdthesis     (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT mastersthesis (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT www           (author|editor|title|booktitle|pages|year|address|journal|volume|number|month|url|ee|cdrom|cite|publisher|note|crossref|isbn|series|school|chapter)*>
<!ELEMENT author    (#PCDATA)>
<!ELEMENT editor    (#PCDATA)>
<!ELEMENT address   (#PCDATA)>
<!ELEMENT title     (sub|sup|i|tt|ref)*>
<!ELEMENT booktitle (#PCDATA)>
<!ELEMENT pages     (#PCDATA)>
<!ELEMENT year      (#PCDATA)>
<!ELEMENT journal   (#PCDATA)>
<!ELEMENT volume    (#PCDATA)>
<!ELEMENT number    (#PCDATA)>
<!ELEMENT month     (#PCDATA)>
<!ELEMENT url       (#PCDATA)>
<!ELEMENT ee        (#PCDATA)>
<!ELEMENT cdrom     (#PCDATA)>
<!ELEMENT cite      (#PCDATA)>
<!ELEMENT school    (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT note      (#PCDATA)>
<!ELEMENT crossref  (#PCDATA)>
<!ELEMENT isbn      (#PCDATA)>
<!ELEMENT chapter   (#PCDATA)>
<!ELEMENT series    (#PCDATA)>
<!ELEMENT ref (sub|sup|i|tt|ref)*>
<!ELEMENT sup (sub|sup|i|tt|ref)*>
<!ELEMENT sub (sub|sup|i|tt|ref)*>
<!ELEMENT i   (sub|sup|i|tt|ref)*>
<!ELEMENT tt  (sub|sup|i|tt|ref)*>

=== lyl123321/MismatchSolution/data/dblp/dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dblp SYSTEM "data/dblp/dblp.dtd">
<dblp>
<article>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</article>
<inproceedings>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</inproceedings>
<proceedings>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</proceedings>
<book>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</book>
<incollection>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</incollection>
<phdthesis>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</phdthesis>
<mastersthesis>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</mastersthesis>
<www>
<author></author>
<editor></editor>
<title>
<sub></sub>
<sup></sup>
<i></i>
<tt></tt>
<ref></ref>
</title>
<booktitle></booktitle>
<pages></pages>
<year></year>
<address></address>
<journal></journal>
<volume></volume>
<number></number>
<month></month>
<url></url>
<ee></ee>
<cdrom></cdrom>
<cite></cite>
<publisher></publisher>
<note></note>
<crossref></crossref>
<isbn></isbn>
<series></series>
<school></school>
<chapter></chapter>
</www>
</dblp>
